dist: bionic

git:
  # set a custom clone depth, so contributor data does not get lost
  # running "git fetch --unshallow" in before_install is also an option
  depth: 9999999

language: node_js
node_js:
  - lts/*

addons:
  apt:
    packages:
      - nsis

services:
  - xvfb

cache:
  apt: true
  directories:
    - node_modules
    - build/cache
  yarn: true

before_install:
  - |
    set -e
    curl -sSL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt-get update -qq && sudo apt-get install -qq -o=Dpkg::Use-Pty=0 --no-install-recommends -y yarn
    shopt -s expand_aliases
    alias yarn=/usr/bin/yarn
    yarn --version

install:
  - export SOURCE_DATE_EPOCH=$(git show -s --format=%ct ${TRAVIS_TAG:-${TRAVIS_COMMIT}})
  - echo "SOURCE_DATE_EPOCH = ${SOURCE_DATE_EPOCH}"
  - if [ "${TRAVIS_TAG}" ]; then yarn cache clean; rm -rf node_modules/ build/cache/; fi
  - yarn install --pure-lockfile --no-progress --non-interactive

script:
  # test and build
  - yarn run grunt webpack:i18n build:prod:coverage
  - yarn run codecov
  # compile and package
  - |
    set -e
    if [ "${TRAVIS_TAG}" ]; then
      # install wine (needed for building Windows releases)
      bash ./build/travis/install-wine.sh
      # finally start building the release
      mkdir dist
      yarn run grunt clean:dist dist:all
    fi

deploy:
  - provider: releases
    api_key: "${RELEASES_API_KEY}"
    file: dist/*{.tar.gz,.zip,.exe,-checksums.txt}
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: node build/travis/update_release.js
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false
  webhooks:
    urls:
      - "${WEBHOOK_GITTER}"
    on_success: change
    on_failure: always
    on_start: never
