language: node_js
sudo: required
dist: trusty

git:
  # set a custom clone depth, so contributor data does not get lost
  # running "git fetch --unshallow" in before_install is also an option
  depth: 9999999

node_js:
  - "6"

cache:
  apt: true
  directories:
    - "node_modules"
    - "bower_components"
    - "build/cache"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"
  - "npm install -g bower grunt-cli"

install:
  - "npm install"

script:
  # test and build
  - "grunt build:prod"

before_deploy:
  # travis "ubuntu trusty" workaround for wine
  # wine is only needed for compiling the application (nw-builder)
  - "sudo dpkg --add-architecture i386"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y wine > /dev/null"
  # compile the application and package it
  # do everything the "dist" grunt task does, but don't build twice
  - "grunt clean:dist compile:all compress checksum:all"

deploy:
  - provider: releases
    api_key:
      secure: "E4l/St08epvsX1NWYN3DI8dyHNus8kV8jqgu6/qK1QMqcORVeAl8Mto84QKGtOujDIo2nEHyxcPn+adbzsuYjKCNinFoc4+UWnvpwQtkHEC7dvZC54fpK86oSQfO0eHrnyjh6KCFf6cYqO2ClEcuFvKe/mTC2Z37xhs59mDF/ME+bA9MoccB13nfVA1aOHOx5QIAC56y6ZQoN0+w0sK9oZIEV3K+L3B7pNuhiSJ97IbPEy5kQMGxRcOazKlx7tkNzzWGBR3b1uwUK8UPBGH1fE66/ZGUxVGY3dHUlec2ZmuOPHMktQUgIiCxUod7D01fRgxjmrJizVNi2X/OQkloOMjb9ZuzAJg2NkEyAVlJ0dcg19j0aG7o0mzZl5UDSV6JhXe4xvaQQ+VBBR6GRs9FZ94YL+BrAAJB+er6c/H5zjK4AMlOhhc7zYJIMNQyDhU5CwkXRpsdGptgtT8Tzpxwpn0TsC4+tqIb5zpFsqKsKXgkwBHoVniPNqeYdl3fmFWGqCtWnpKwBPTly3DZjFMQcBspy48byFadASbCfVG50mUi/Mtv/tQ51suG8B+G3GDvL4MZmAdPyhcgo29tLEiYEqCmoW2P/HyyDgwZ0x0zuBBDcuvS6p3BFwCjxSA3Jl+rLR50A7rgCXB2p9uFLZpOGRQ3se8tOEUqNuEy77fwXwk="
    file: "dist/*"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
