blank_issues_enabled: false
contact_links:
  - name: "Streamlink"
    about: "This is the Streamlink Twitch GUI repository. Anything Streamlink related belongs on the Streamlink repository."
    url: https://github.com/streamlink/streamlink
  - name: "Help"
    about: "The issue tracker is only meant for bug reports and feature requests. Please ask your questions on the discussions forum and look for already existing answers."
    url: https://github.com/streamlink/streamlink-twitch-gui/discussions
  - name: "Wiki"
    about: "Please refer to Streamlink Twitch GUI's wiki first before opening new issues or asking questions."
    url: https://github.com/streamlink/streamlink-twitch-gui/wiki
  - name: "Gitter channel"
    about: "Get in touch with other Streamlink Twitch GUI users."
    url: https://gitter.im/streamlink/streamlink-twitch-gui
  - name: "Matrix channel (Gitter bridge)"
    about: "Get in touch with other Streamlink Twitch GUI users."
    url: https://matrix.to/#/#streamlink_streamlink-twitch-gui:gitter.im
