name: Test, build and deploy

on:
  push: {}
  pull_request: {}

env:
  CI: true
  NODE_VERSION: 12

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Git config on Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Prepare env vars
        shell: bash
        run: |
          echo ::set-env name=YARN_CACHE_FOLDER::$(yarn cache dir)
      - name: Yarn cache
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: yarn-${{ matrix.os }}-${{ hashFiles('yarn.lock') }}
      - name: NW.js cache
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: actions/cache@v2
        with:
          path: build/cache/
          key: nwjs-${{ matrix.os }}-${{ hashFiles('src/config/main.json') }}
      - name: Install dependencies
        shell: bash
        run: yarn install --pure-lockfile --no-progress --non-interactive
      - name: I18n
        run: yarn run grunt webpack:i18n
      - name: Test
        shell: bash
        run: |
          if [[ "$(uname)" == "Linux" ]]; then
            xvfb-run --auto-servernum yarn run grunt test:coverage
          else
            yarn run grunt test:coverage
          fi
      - name: Build
        run: yarn run grunt clean:tmp_prod webpack:prod
      - name: Upload coverage data
        uses: codecov/codecov-action@v1
        with:
          name: os:${{ matrix.os }}
          file: build/tmp/coverage/coverage.json

  release:
    name: New release
    if: github.repository == 'streamlink/streamlink-twitch-gui' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Prepare env vars
        run: |
          echo ::set-env name=SOURCE_DATE_EPOCH::$(git show -s --format=%ct "${GITHUB_REF}")
      - name: Install dependencies
        run: |
          yarn install --pure-lockfile --no-progress --non-interactive
          sudo apt install pigz nsis appstream{,-util}
          ./.github/workflows/install-wine.sh
          ./.github/workflows/build-squashfs-tools.sh
      - name: Build
        run: yarn run grunt clean:tmp_prod webpack:prod
      - name: Compile & package
        run: yarn run grunt clean:dist dist:all
      - name: Deploy
        env:
          RELEASES_API_KEY: ${{ secrets.RELEASES_API_KEY }}
        run: yarn run grunt deploy:github
